var MSG = {
xStepper:"xステッパー",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c インジケータ",
  nminicatSerialLCD_I2C:"ディスプレイ84x84",
  catST2046:"ディスプレイ2.8",
  fingerprinting:"指紋",
  tensorsensor:"ロードセル",
  electrocardiography:"心電計",
  catInOut:"入力/出力",
  catDigital:"デジタル",
  catAnalog:"アナログ",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"ソフトシリアル",
  ibuttonds1990:"連絡キー",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"モーター",
  catMotorMRT:"ドライバー",
  catServoRot:"サーボ 360",
  stepcatServoRot:"サーボ 180S",
  catStepper:"ステッピング 4",
  catStepper28BYJ:"ステッピング 5",
  catServo:"サーボ 180",
  catStorage:"保管場所",
  catLedStrip:"Led 住所",
  catST7735:"TFT 展示する",
  catTM1637:"4/7с 展示する",
  catRTCDS3231:"モジュール DS3231",
  catRTCDS1302:"モジュール DS1302",
  catCommunication:"コミュニケーション",
  catMAX7219_7D:"8/7с 展示する",
  catMAX7219_LM:"行列 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"地図 SD",
  catSimpleSensorsALL:"センサー",
  catSimpleSensors:"センサー 1",
  catSimpleSensors2: "センサー 2",
  catSimpleSensors3: "センサー 3",
  catOtherSensors:"その他のセンサー",
  catOtherActuators:"サウンドモジュール",
  catRadioTEA5767:"無線モジュール",
  catDFPlayerMP3:"MP3 プレイヤー",
  catKeypad:"キーボード",
  catds18b20:"体温計",
  catADXL345:"加速度計",
  catTCS3200:"カラー検出器",
  catCamera:"Camera VC0706",
  catHMC5883:"コンパス",
  bmpcatHMC5883:"気圧計",
  catRotaryEncoder:"エンコーダー",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"出力モジュール",
  catDisplay:"展示する",
  catRFID:"カード",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"展示する 16x2",
  catSerialLCDmb2:"展示する 128×64",
  catSerialLCD_I2C:"展示する 16x2 I2C",
  minicatSerialLCD_I2C:"ミニ 展示する",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"小文字", 
  catInterruptExt:"中断",
  catDivers:"メインサイクル",
  title: "日本人",
  blocks: "Block",
  linkTooltip: "保存してブロックにリンクします。",
  runTooltip: "名前を付けて保存 ino",
  saveXMLTooltip:"保存する XML",
  loadXMLTooltip:"アップロードする XML",
  copycodeTooltip:"コードをコピー Arduino",
  badCode: "プログラムエラー:\n%1",
  timeout: "実行反復の最大数を超えました。",
  discard: "削除する %1 ブロック?",
  trashTooltip: "すべてのブロックを削除します。",
  catLogic: "論理",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "サイクル",
  catMath: "数学",
  catText: "テキスト",
  catArray:"配列",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"時間",
  catGenericTime:"システム",
  catAllVar:"変数",
  catVariables: "シンプル",
  catFunctions: "機能",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
