var MSG = {
xStepper:"× السائر",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c مؤشر",
  nminicatSerialLCD_I2C:"عرض 84",
  catST2046:"عرض 2.8",
  fingerprinting:"البصمات",
  tensorsensor:"استشعار تنسو",
  electrocardiography:"مخطاط القلب",
  catInOut:"الدخول / الخروج",
  catDigital:"رقمي",
  catAnalog:"التناظرية",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"مسلسل ناعم",
  ibuttonds1990:"مفتاح الاتصال",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"المحركات",
  catMotorMRT:"السائقين",
  catServoRot:"مضاعفات 360",
  stepcatServoRot:"أجهزة 180S",
  catStepper:"الخطوة 4",
  catStepper28BYJ:"الخطوة 5",
  catServo:"مضاعفات 180",
  catStorage:"موقع التخزين",
  catLedStrip:"Led عنوان",
  catST7735:"TFT عرض",
  catTM1637:"4/7с عرض",
  catRTCDS3231:"وحدة DS3231",
  catRTCDS1302:"وحدة DS1302",
  catCommunication:"وحدات الاتصالات",
  catMAX7219_7D:"8/7с عرض",
  catMAX7219_LM:"قالب 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"الخريطة SD",
  catSimpleSensorsALL:"أجهزة الاستشعار",
  catSimpleSensors:"أجهزة الاستشعار 1",
  catSimpleSensors2: "أجهزة الاستشعار 2",
  catSimpleSensors3: "أجهزة الاستشعار 3",
  catOtherSensors:"أجهزة استشعار أخرى",
  catOtherActuators:"وحدات الصوت",
  catRadioTEA5767:"وحدة الراديو",
  catDFPlayerMP3:"MP3 لاعب",
  catKeypad:"لوحة المفاتيح",
  catds18b20:"ميزان الحرارة",
  catADXL345:"التسارع",
  catTCS3200:"كاشف اللون",
  catCamera:"Camera VC0706",
  catHMC5883:"بوصلة",
  bmpcatHMC5883:"مقياس الضغط الجوي",
  catRotaryEncoder:"التشفير",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"وحدات الخروج",
  catDisplay:"يعرض",
  catRFID:"وحدة البطاقة",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"عرض 16x2",
  catSerialLCDmb2:"عرض 128×64",
  catSerialLCD_I2C:"عرض 16x2 I2C",
  minicatSerialLCD_I2C:"عرض صغير",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"صغيرة", 
  catInterruptExt:"إعاقة",
  catDivers:"الدورات الرئيسية",
  title: "العربية",
  blocks: "Block",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "حفظ وربط لبنات.",
  runTooltip: "حفظ باسم ino",
  saveXMLTooltip:"احتفظ XML",
  loadXMLTooltip:"تحميل XML",
  copycodeTooltip:"نسخ الكود Arduino",
  badCode: "خطأ في البرنامج:\n%1",
  timeout: "تم تجاوز الحد الأقصى لعدد مرات تكرار التنفيذ.",
  discard: "حذف %1 كتل?",
  trashTooltip: "حذف جميع الكتل.",
  catLogic: "منطق",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "دورة",
  catMath: "الرياضيات",
  catText: "نص",
  catArray:"المصفوفات",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"وقت",
  catGenericTime:"نظام",
  catAllVar:"المتغيرات",
  catVariables: "بسيط",
  catFunctions: "وظائف",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
