var MSG = {
xStepper:"x步進",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c 指示符",
  nminicatSerialLCD_I2C:"展示架 84x84",
  catST2046:"展示架 2.8",
  fingerprinting:"指紋識別",
  tensorsensor:"稱重傳感器",
  electrocardiography:"心電圖儀",
  catInOut:"進入/退出",
  catDigital:"數字化",
  catAnalog:"模擬量",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"軟串口",
  ibuttonds1990:"聯絡鍵",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"馬達",
  catMotorMRT:"車手",
  catServoRot:"伺服 360",
  stepcatServoRot:"伺服 180S",
  catStepper:"踏步 4",
  catStepper28BYJ:"踏步 5",
  catServo:"伺服 180",
  catStorage:"存放地點",
  catLedStrip:"Led 住址",
  catST7735:"TFT 展示架",
  catTM1637:"4/7с 展示架",
  catRTCDS3231:"模組 DS3231",
  catRTCDS1302:"模組 DS1302",
  catCommunication:"通訊模塊",
  catMAX7219_7D:"8/7с 展示架",
  catMAX7219_LM:"矩陣 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"SD卡",
  catSimpleSensorsALL:"感測器",
  catSimpleSensors:"感測器 1",
  catSimpleSensors2: "感測器 2",
  catSimpleSensors3: "感測器 3",
  catOtherSensors:"其他傳感器",
  catOtherActuators:"聲音模塊",
  catRadioTEA5767:"無線電模塊",
  catDFPlayerMP3:"MP3 播放器",
  catKeypad:"琴鍵",
  catds18b20:"體溫計",
  catADXL345:"加速度計",
  catTCS3200:"顏色檢測器",
  catCamera:"Camera VC0706",
  catHMC5883:"指南針",
  bmpcatHMC5883:"氣壓計",
  catRotaryEncoder:"編碼器",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"出口模塊",
  catDisplay:"展示架",
  catRFID:"卡模塊",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"展示架 16x2",
  catSerialLCDmb2:"展示架 128×64",
  catSerialLCD_I2C:"展示架 16x2 I2C",
  minicatSerialLCD_I2C:"迷你顯示器",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"小寫字母", 
  catInterruptExt:"打斷",
  catDivers:"主要周期",
  title: "中國人",
  blocks: "Block",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "保存並鏈接到塊。",
  runTooltip: "另存為 ino",
  saveXMLTooltip:"保存到 XML",
  loadXMLTooltip:"資料下載 XML",
  copycodeTooltip:"複製代碼 Arduino",
  badCode: "程式錯誤:\n%1",
  timeout: "已超過最大執行迭代次數。",
  discard: "刪掉 %1 塊?",
  trashTooltip: "刪除所有塊。",
  catLogic: "邏輯學",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "循環數",
  catMath: "數學",
  catText: "文字內容",
  catArray:"數組",
  catLists: "清單",
  catColour: "色澤",
  catTime:"時間",
  catGenericTime:"系統名稱",
  catAllVar:"變數",
  catVariables: "簡單的",
  catFunctions: "功能介紹",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
