var MSG = {
xStepper:"x Stepper",
leonardo:"Leonardo",
  catInOut:"Input/Output",
  nminicatSerialLCD_I2C:"Nokia 5110 84x84",
  catST2046:"TFT Touch 240x320",
  fingerprinting:"Fingerprinting",
  tensorsensor:"Tensor sensor",
  electrocardiography:"Cardiograph",
  catDigital:"Digital",
  catAnalog:"Analog",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motors",
  catMotorMRT:"Motor Shield",
  catServoRot:"Rotation Servo",
  stepcatServoRot:"Step Servo",
  catStepper:"Other steppers",
  catStepper28BYJ:"Stepper 28BYJ",
  catServo:"Servo",
  catStorage:"Storage",
  catLedStrip:"Led Strip",
  catST7735:"TFT ST7735",
  catTM1637:"TM1637 display",
  catRTCDS3231:"RTC DS3231",
  catRTCDS1302:"RTC DS1302",
  catCommunication:"Communication modules",
  catMAX7219_7D:"MAX7219 7digit",
  catMAX7219_LM:"MAX7219 Led Matrix",
  catEEprom:"EEPROM",
  catmicroSD:"Micro SD",
  catSimpleSensorsALL:"Sensors",
  catSimpleSensors:"Sensors I",
  catSimpleSensors2: "Sensors II",
  catSimpleSensors3: "Sensors III",
  catOtherSensors:"Other sensors",
  catOtherActuators:"Sound modules",
  catRadioTEA5767:"Radio TEA5767",
  catDFPlayerMP3:"MP3 Player",
  catKeypad:"Keypad",
  catds18b20:"DS18B20",
  catADXL345:"ADXL345 Accel",
  catTCS3200:"TCS3200 Color",
  catCamera:"Camera VC0706",
  catHMC5883:"HMC5883 Compass",
  bmpcatHMC5883:"BMP",
  catRotaryEncoder:"Rotary Encoder",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Exit modules",
  catDisplay:"Displays",
  catRFID:"RFID MFRC522",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"LCD 16x2 20x4",
  catSerialLCDmb23:"4/7c indicator",
  catSerialLCDmb2:"LCD 128×64",
  catSerialLCD_I2C:"LCD 16x2 20x4 I2C",
  minicatSerialLCD_I2C:"Mini 128×64",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"String", 
  catInterruptExt:"Interrupt",
  catDivers:"Main cycles",
  title: "English",
  blocks: "Block",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Save as ino",
  saveXMLTooltip:"Save XML",
  loadXMLTooltip:"Download XML",
  copycodeTooltip:"Copy code Arduino",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Delete all %1 blocks?",
  trashTooltip: "Delete all blocks.",
  catLogic: "Logics",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"Radio Frequency",
  catRF24L01:"NRF 24L01",
  catLoops: "Cycle",
  catMath: "Maths",
  catText: "Text",
  catArray:"Array",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Time",
  catGenericTime:"Generic",
  catAllVar:"Variables",
  catVariables: "Simple variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
