var MSG = {
xStepper:"x pas à pas",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c indicateur",
  nminicatSerialLCD_I2C:"Affichage 84x84",
  catST2046:"Affichage 2.8",
  fingerprinting:"Empreinte digitale",
  tensorsensor:"Capteur Tenso",
  electrocardiography:"Cardiographe",
  catInOut:"Entrée / sortie",
  catDigital:"Numérique",
  catAnalog:"Analogique",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Moteurs",
  catMotorMRT:"Les chauffeurs",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Marcher 4",
  catStepper28BYJ:"Marcher 5",
  catServo:"Servo 180",
  catStorage:"Lieu de stockage",
  catLedStrip:"Led Adresse",
  catST7735:"TFT Affichage",
  catTM1637:"4/7с Affichage",
  catRTCDS3231:"Module DS3231",
  catRTCDS1302:"Module DS1302",
  catCommunication:"Communication",
  catMAX7219_7D:"8/7с Affichage",
  catMAX7219_LM:"Matrice 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Carte SD",
  catSimpleSensorsALL:"Capteurs",
  catSimpleSensors:"Capteurs 1",
  catSimpleSensors2: "Capteurs 2",
  catSimpleSensors3: "Capteurs 3",
  catOtherSensors:"Autres capteurs",
  catOtherActuators:"Modules de sons",
  catRadioTEA5767:"Module radio",
  catDFPlayerMP3:"MP3 Joueur",
  catKeypad:"Clavier",
  catds18b20:"Thermomètre",
  catADXL345:"Accéléromètre",
  catTCS3200:"Détecteur de couleur",
  catCamera:"Camera VC0706",
  catHMC5883:"Boussole",
  bmpcatHMC5883:"Baromètre",
  catRotaryEncoder:"Codeur",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Modules de sortie",
  catDisplay:"Affiche",
  catRFID:"Module de carte",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Affichage 16x2",
  catSerialLCDmb2:"Affichage 128×64",
  catSerialLCD_I2C:"Affichage 16x2 I2C",
  minicatSerialLCD_I2C:"Mini écran",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Minuscule", 
  catInterruptExt:"Interruption",
  catDivers:"Cycles principaux",
  title: "Français",
  blocks: "Block",
  linkTooltip: "Sauvegarder et lier aux blocs.",
  runTooltip: "Enregistrer sous ino",
  saveXMLTooltip:"Enregistrer XML",
  loadXMLTooltip:"Télécharger XML",
  copycodeTooltip:"Copier le code Arduino",
  badCode: "Erreur de programme:\n%1",
  timeout: "Le nombre maximum d'itérations d'exécution a été dépassé.",
  discard: "Supprimer %1 des blocs?",
  trashTooltip: "Supprimer tous les blocs.",
  catLogic: "La logique",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Cycle",
  catMath: "Maths",
  catText: "Texte",
  catArray:"Tableaux",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Le temps",
  catGenericTime:"Système",
  catAllVar:"Variables",
  catVariables: "Simple",
  catFunctions: "Fonctions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
