var MSG = {
xStepper:"एक्स स्टेपर",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c सूचक",
  nminicatSerialLCD_I2C:"प्रदर्शन 84x84",
  catST2046:"प्रदर्शन 2.8",
  fingerprinting:"फिंगरप्रिंटिंग",
  tensorsensor:"टेंसो सेंसर",
  electrocardiography:"कार्डियग्रफ़ी",
  catInOut:"प्रवेश / निकास",
  catDigital:"डिजिटल",
  catAnalog:"अनुरूप",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"संपर्क कुंजी",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"मोटर्स",
  catMotorMRT:"ड्राइवरों",
  catServoRot:"इमदादी 360",
  stepcatServoRot:"इमदादी 180S",
  catStepper:"स्टेपर 4",
  catStepper28BYJ:"स्टेपर 5",
  catServo:"इमदादी 180",
  catStorage:"भंडारण स्थान",
  catLedStrip:"पता एलईडी पट्टी",
  catST7735:"TFT प्रदर्शन",
  catTM1637:"4/7с प्रदर्शन",
  catRTCDS3231:"मॉड्यूल DS3231",
  catRTCDS1302:"मॉड्यूल DS1302",
  catCommunication:"संचार मॉड्यूल",
  catMAX7219_7D:"8/7с प्रदर्शन",
  catMAX7219_LM:"मैट्रिक्स 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"नक्शा SD",
  catSimpleSensorsALL:"सेंसर",
  catSimpleSensors:"सेंसर 1",
  catSimpleSensors2: "सेंसर 2",
  catSimpleSensors3: "सेंसर 3",
  catOtherSensors:"अन्य सेंसर",
  catOtherActuators:"ध्वनि मॉड्यूल",
  catRadioTEA5767:"रेडियो मॉड्यूल",
  catDFPlayerMP3:"MP3 खिलाड़ी",
  catKeypad:"कीबोर्ड",
  catds18b20:"थर्मामीटर",
  catADXL345:"संतुलन",
  catTCS3200:"रंग डिटेक्टर",
  catCamera:"Camera VC0706",
  catHMC5883:"परकार",
  bmpcatHMC5883:"बैरोमीटर",
  catRotaryEncoder:"एनकोडर",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"आउटपुट मॉड्यूल",
  catDisplay:"प्रदर्शित करता है",
  catRFID:"कार्ड मॉड्यूल",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"प्रदर्शन 16x2",
  catSerialLCDmb2:"प्रदर्शन 128×64",
  catSerialLCD_I2C:"प्रदर्शन 16x2 I2C",
  minicatSerialLCD_I2C:"मिनी प्रदर्शन",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"लोअरकेस", 
  catInterruptExt:"व्यवधान",
  catDivers:"मुख्य चक्र",
  title: "हिन्दी",
  blocks: "Block",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "सहेजें और ब्लॉकों से लिंक करें।",
  runTooltip: "के रूप में सहेजें ino",
  saveXMLTooltip:"बनाए रखने के XML",
  loadXMLTooltip:"डाउनलोड XML",
  copycodeTooltip:"कोड को कॉपी करें Arduino",
  badCode: "कार्यक्रम की त्रुटि:\n%1",
  timeout: "निष्पादन पुनरावृत्तियों की अधिकतम संख्या पार हो गई है।",
  discard: "हटाएं %1 ब्लॉक?",
  trashTooltip: "सभी ब्लॉक हटाएं।",
  catLogic: "तर्क",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "चक्र",
  catMath: "गणित",
  catText: "टेक्स्ट",
  catArray:"सरणियों",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"समय",
  catGenericTime:"प्रणाली",
  catAllVar:"चर",
  catVariables: "सरल",
  catFunctions: "कार्यों",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
