var MSG = {
xStepper:"x paso",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c indicador",
  nminicatSerialLCD_I2C:"Display 84x84",
  catST2046:"Display 2.8",
  fingerprinting:"Huellas dactilares",
  tensorsensor:"Sensor Tenso",
  electrocardiography:"Cardiógrafo",
  catInOut:"Entrada/Salida",
  catDigital:"Digital",
  catAnalog:"Análogo",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motores",
  catMotorMRT:"Conductores",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Motor paso 4",
  catStepper28BYJ:"Motor paso 5",
  catServo:"Servo 180",
  catStorage:"Memoria",
  catLedStrip:"Led Dirección",
  catST7735:"TFT Display",
  catTM1637:"4/7с Display",
  catRTCDS3231:"Modulo DS3231",
  catRTCDS1302:"Modulo DS1302",
  catCommunication:"Comunicación",
  catMAX7219_7D:"8/7с Display",
  catMAX7219_LM:"Matriz 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Flash SD",
  catSimpleSensorsALL:"Sensores",
  catSimpleSensors:"Sensores 1",
  catSimpleSensors2: "Sensores 2",
  catSimpleSensors3: "Sensores 3",
  catOtherSensors:"Otros sensores",
  catOtherActuators:"Módulos de sonido",
  catRadioTEA5767:"Radio",
  catDFPlayerMP3:"MP3 Jugador",
  catKeypad:"Teclado",
  catds18b20:"Termómetro",
  catADXL345:"Acelerómetro",
  catTCS3200:"Detector de color",
  catCamera:"Camera VC0706",
  catHMC5883:"Brújula",
  bmpcatHMC5883:"Barómetro",
  catRotaryEncoder:"Codificador",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Módulos de salida",
  catDisplay:"Display",
  catRFID:"Tarjeta",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Display 16x2",
  catSerialLCDmb2:"Display 128×64",
  catSerialLCD_I2C:"Display 16x2 I2C",
  minicatSerialLCD_I2C:"Mini Display",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"En minúscula", 
  catInterruptExt:"Interrupción",
  catDivers:"Ciclos principales",
  title: "Español",
  blocks: "Block",
  linkTooltip: "Guardar y vincular a bloques.",
  runTooltip: "Guardar como ino",
  saveXMLTooltip:"Guardar XML",
  loadXMLTooltip:"Descargar XML",
  copycodeTooltip:"Copiar Código Arduino",
  badCode: "Error del programa:\n%1",
  timeout: "Se ha excedido el número máximo de iteraciones de ejecución.",
  discard: "Eliminar %1 bloques?",
  trashTooltip: "Eliminar todos los bloques.",
  catLogic: "La lógica",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Ciclo",
  catMath: "Matemáticas",
  catText: "Texto",
  catArray:"Matrices",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Tiempo",
  catGenericTime:"Sistema",
  catAllVar:"Variables",
  catVariables: "Simple",
  catFunctions: "Las funciones",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
