var MSG = {
xStepper:"x Stepper",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c indicatore",
  nminicatSerialLCD_I2C:"Display 84x84",
  catST2046:"Display 2.8",
  fingerprinting:"Fingerprinting",
  tensorsensor:"Sensore Tenso",
  electrocardiography:"Cardiografo",
  catInOut:"Entrata / Uscita",
  catDigital:"Digitale",
  catAnalog:"Analogico",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motori",
  catMotorMRT:"Driver",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Stepper 4",
  catStepper28BYJ:"Stepper 5",
  catServo:"Servo 180",
  catStorage:"Conservazione",
  catLedStrip:"LED Indirizzabile",
  catST7735:"TFT Display",
  catTM1637:"4/7с Display",
  catRTCDS3231:"Modulo DS3231",
  catRTCDS1302:"Modulo DS1302",
  catCommunication:"Comunicazione",
  catMAX7219_7D:"8/7с Display",
  catMAX7219_LM:"Matrice 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Scheda SD",
  catSimpleSensorsALL:"Sensori",
  catSimpleSensors:"Sensori 1",
  catSimpleSensors2: "Sensori 2",
  catSimpleSensors3: "Sensori 3",
  catOtherSensors:"Altri sensori",
  catOtherActuators:"Moduli audio",
  catRadioTEA5767:"Radio",
  catDFPlayerMP3:"MP3 Player",
  catKeypad:"Tastiera",
  catds18b20:"Termometro",
  catADXL345:"Accelerometro",
  catTCS3200:"Rivelatore di colore",
  catCamera:"Camera VC0706",
  catHMC5883:"Bussola",
  bmpcatHMC5883:"Barometro",
  catRotaryEncoder:"Encoder",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Moduli dell'uscita",
  catDisplay:"Display",
  catRFID:"Modulo Di Carta",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Display 16x2",
  catSerialLCDmb2:"Display 128×64",
  catSerialLCD_I2C:"Display 16x2 I2C",
  minicatSerialLCD_I2C:"Mini display",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Minuscolo", 
  catInterruptExt:"Interruzione",
  catDivers:"Cicli principali",
  title: "Italiano",
  blocks: "Block",
  linkTooltip: "Salva e collega ai blocchi.",
  runTooltip: "Salva in formato ino",
  saveXMLTooltip:"Mantenere XML",
  loadXMLTooltip:"Caricare XML",
  copycodeTooltip:"Copia Codice Arduino",
  badCode: "Errore del programma:\n%1",
  timeout: "È stato superato il numero massimo di iterazioni di esecuzione.",
  discard: "Rimuovere %1 blocchi?",
  trashTooltip: "Rimuovere tutti i blocchi.",
  catLogic: "Logica",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Ciclo",
  catMath: "Matematica",
  catText: "Testo",
  catArray:"Massicci",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Tempo",
  catGenericTime:"Sistemico",
  catAllVar:"Variabili",
  catVariables: "Semplici",
  catFunctions: "Funzioni",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
