var MSG = {
xStepper:"x Stepper",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c kiashiria",
  nminicatSerialLCD_I2C:"Onyesha 84x84",
  catST2046:"Onyesha 2.8",
  fingerprinting:"Uchapaji wa vidole",
  tensorsensor:"Sensor ya Tenso",
  electrocardiography:"Cardiograph",
  catInOut:"Kuingia / Kutoka",
  catDigital:"Dijiti",
  catAnalog:"Analog",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motors",
  catMotorMRT:"Madereva",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Kupiga hatua 4",
  catStepper28BYJ:"Kupiga hatua 5",
  catServo:"Servo 180",
  catStorage:"Mahali pa kuhifadhi",
  catLedStrip:"Led Anwani",
  catST7735:"TFT Onyesha",
  catTM1637:"4/7с Onyesha",
  catRTCDS3231:"Moduli DS3231",
  catRTCDS1302:"Moduli DS1302",
  catCommunication:"Mawasiliano",
  catMAX7219_7D:"8/7с Onyesha",
  catMAX7219_LM:"Matrix 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Kadi ya SD",
  catSimpleSensorsALL:"Sensorer",
  catSimpleSensors:"Sensorer 1",
  catSimpleSensors2: "Sensorer 2",
  catSimpleSensors3: "Sensorer 3",
  catOtherSensors:"Sensorer zingine",
  catOtherActuators:"Moduli za sauti",
  catRadioTEA5767:"Moduli ya Redio",
  catDFPlayerMP3:"MP3 Mchezaji",
  catKeypad:"Kibodi",
  catds18b20:"Thermometer",
  catADXL345:"Accelerometer",
  catTCS3200:"Kizuizi cha rangi",
  catCamera:"Camera VC0706",
  catHMC5883:"Kampasi",
  bmpcatHMC5883:"Barometer",
  catRotaryEncoder:"Encoder",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Moduli za matokeo",
  catDisplay:"Maonyesho",
  catRFID:"Moduli ya Kadi",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Onyesha 16x2",
  catSerialLCDmb2:"Onyesha 128×64",
  catSerialLCD_I2C:"Onyesha 16x2 I2C",
  minicatSerialLCD_I2C:"Maonyesho ya mini",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Chini ya chini", 
  catInterruptExt:"Kuingilia",
  catDivers:"Mzunguko kuu",
  title: "Kiswahili",
  blocks: "Block",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "Okoa na unganisha kwa vitalu.",
  runTooltip: "Okoa kama ino",
  saveXMLTooltip:"Okoa XML",
  loadXMLTooltip:"Pakua XML",
  copycodeTooltip:"Nakili nambari Arduino",
  badCode: "Kosa la mpango:\n%1",
  timeout: "Idadi kubwa ya utaftaji wa utekelezaji umezidi.",
  discard: "Futa %1 vizuizi?",
  trashTooltip: "Futa vizuizi vyote.",
  catLogic: "Mantiki",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Mzunguko",
  catMath: "Math",
  catText: "Maandishi",
  catArray:"Kufika",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Wakati",
  catGenericTime:"Mfumo",
  catAllVar:"Vighairi",
  catVariables: "Rahisi",
  catFunctions: "Kazi",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
