var MSG = {
xStepper:"x 스테퍼",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c 지시자",
  nminicatSerialLCD_I2C:"디스플레이 84x84",
  catST2046:"디스플레이 2.8",
  fingerprinting:"지문",
  tensorsensor:"텐소 센서",
  electrocardiography:"심전도",
  catInOut:"입국",
  catDigital:"디지털",
  catAnalog:"아날로그",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"연락 키",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"모터",
  catMotorMRT:"드라이버",
  catServoRot:"서보 360",
  stepcatServoRot:"서보 180S",
  catStepper:"스테퍼 모터 4",
  catStepper28BYJ:"스테퍼 모터 5",
  catServo:"서보 180",
  catStorage:"보관 위치",
  catLedStrip:"지도 된 주소",
  catST7735:"TFT 디스플레이",
  catTM1637:"4/7с 디스플레이",
  catRTCDS3231:"모듈 DS3231",
  catRTCDS1302:"모듈 DS1302",
  catCommunication:"통신 모듈",
  catMAX7219_7D:"8/7с 디스플레이",
  catMAX7219_LM:"매트릭스 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"메모리 카드 SD",
  catSimpleSensorsALL:"센서",
  catSimpleSensors:"센서 1",
  catSimpleSensors2: "센서 2",
  catSimpleSensors3: "센서 3",
  catOtherSensors:"다른 센서",
  catOtherActuators:"사운드 모듈",
  catRadioTEA5767:"라디오 모듈",
  catDFPlayerMP3:"MP3 선수",
  catKeypad:"키보드",
  catds18b20:"온도계",
  catADXL345:"가속도계",
  catTCS3200:"색감지기",
  catCamera:"Camera VC0706",
  catHMC5883:"나침반",
  bmpcatHMC5883:"기압계",
  catRotaryEncoder:"엔코더",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"출력 모듈",
  catDisplay:"디스플레이",
  catRFID:"카드 모듈",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"디스플레이 16x2",
  catSerialLCDmb2:"디스플레이 128×64",
  catSerialLCD_I2C:"디스플레이 16x2 I2C",
  minicatSerialLCD_I2C:"미니 디스플레이",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"문자열 변수", 
  catInterruptExt:"중단",
  catDivers:"메인 사이클",
  title: "한국인",
  blocks: "Block",// 차단 ",// 12 블록",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "저장하고 블록에 연결하십시오.",
  runTooltip: "다른 이름으로 저장 ino",
  saveXMLTooltip:"저장 XML",
  loadXMLTooltip:"다운로드 XML",
  copycodeTooltip:"코드 복사 Arduino",
  badCode: "프로그램 오류:\n%1",
  timeout: "최대 실행 반복을 초과했습니다.",
  discard: "삭제 %1 블록?",
  trashTooltip: "모든 블록을 삭제하십시오.",
  catLogic: "논리",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "사이클",
  catMath: "수학",
  catText: "문자",
  catArray:"배열",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"시간",
  catGenericTime:"시스템",
  catAllVar:"변수",
  catVariables: "단순",
  catFunctions: "기능",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
