var MSG = {
xStepper:"x Stepper",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c penunjuk",
  nminicatSerialLCD_I2C:"Paparan 84x84",
  catST2046:"Paparan 2.8",
  fingerprinting:"Cap jari",
  tensorsensor:"Sensor Tenso",
  electrocardiography:"Kardiografi",
  catInOut:"Kemasukan / Keluar",
  catDigital:"Digital",
  catAnalog:"Analog",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motosikal",
  catMotorMRT:"Pemandu",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Motor stepper 4",
  catStepper28BYJ:"Motor stepper 5",
  catServo:"Servo 180",
  catStorage:"Lokasi simpanan",
  catLedStrip:"Alamat Led",
  catST7735:"TFT Paparan",
  catTM1637:"4/7с Paparan",
  catRTCDS3231:"Modul DS3231",
  catRTCDS1302:"Modul DS1302",
  catCommunication:"Modul komunikasi",
  catMAX7219_7D:"8/7с Paparan",
  catMAX7219_LM:"Matrix 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Kad memori SD",
  catSimpleSensorsALL:"Sensor",
  catSimpleSensors:"Sensor 1",
  catSimpleSensors2: "Sensor 2",
  catSimpleSensors3: "Sensor 3",
  catOtherSensors:"Sensor lain",
  catOtherActuators:"Modul bunyi",
  catRadioTEA5767:"Modul radio",
  catDFPlayerMP3:"MP3 Pemain",
  catKeypad:"Papan kekunci",
  catds18b20:"Termometer",
  catADXL345:"Akselerometer",
  catTCS3200:"Pengesan warna",
  catCamera:"Camera VC0706",
  catHMC5883:"Kompas",
  bmpcatHMC5883:"Barometer",
  catRotaryEncoder:"Pengekod",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Keluar modul",
  catDisplay:"Memaparkan",
  catRFID:"Modul Kad",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Paparan 16x2",
  catSerialLCDmb2:"Paparan 128×64",
  catSerialLCD_I2C:"Paparan 16x2 I2C",
  minicatSerialLCD_I2C:"Paparan mini",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Huruf kecil", 
  catInterruptExt:"Gangguan",
  catDivers:"Pusingan utama",
  title: "Malay",
  blocks: "Block",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "Simpan dan hubungkan ke blok.",
  runTooltip: "Simpan sebagai ino",
  saveXMLTooltip:"Simpan XML",
  loadXMLTooltip:"Muat turun XML",
  copycodeTooltip:"Salin kod Arduino",
  badCode: "Ralat program:\n%1",
  timeout: "Bilangan lelaran pelaksanaan maksimum telah melebihi.",
  discard: "Padam %1 blok?",
  trashTooltip: "Padam semua blok.",
  catLogic: "Logik",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Kitaran",
  catMath: "Matematik",
  catText: "Teks",
  catArray:"Arrays",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Masa",
  catGenericTime:"Sistem",
  catAllVar:"Pembolehubah",
  catVariables: "Mudah",
  catFunctions: "Fungsi",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
