var MSG = {
xStepper:"x Stepper",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c indicator",
  nminicatSerialLCD_I2C:"Tonen 84x84",
  catST2046:"Tonen 2.8",
  fingerprinting:"Fingerprinting",
  tensorsensor:"Tensosensor",
  electrocardiography:"Cardiograph",
  catInOut:"Binnenkomst / uitgang",
  catDigital:"Digitaal",
  catAnalog:"Analoge",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motor",
  catMotorMRT:"Stuurprogramma",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Stepper 4",
  catStepper28BYJ:"Stepper 5",
  catServo:"Servo 180",
  catStorage:"Opslaglocatie",
  catLedStrip:"Led Adres",
  catST7735:"TFT Weergegeven",
  catTM1637:"4/7с Weergegeven",
  catRTCDS3231:"Module DS3231",
  catRTCDS1302:"Module DS1302",
  catCommunication:"Communicatiemodule",
  catMAX7219_7D:"8/7с Weergegeven",
  catMAX7219_LM:"Matrix 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Kaart SD",
  catSimpleSensorsALL:"Sensor",
  catSimpleSensors:"Sensor 1",
  catSimpleSensors2: "Sensor 2",
  catSimpleSensors3: "Sensor 3",
  catOtherSensors:"Ander Sensor",
  catOtherActuators:"Geluidsmodule",
  catRadioTEA5767:"Radiomodule",
  catDFPlayerMP3:"MP3 Speler",
  catKeypad:"Toetsenbord",
  catds18b20:"Thermometer",
  catADXL345:"Versnellingsmeter",
  catTCS3200:"Kleur detector",
  catCamera:"Camera VC0706",
  catHMC5883:"Kompas",
  bmpcatHMC5883:"Barometer",
  catRotaryEncoder:"Encoder",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Uitvoermodules",
  catDisplay:"Weergegeven",
  catRFID:"Kaartmodule",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Weergegeven 16x2",
  catSerialLCDmb2:"Weergegeven 128×64",
  catSerialLCD_I2C:"Weergegeven 16x2 I2C",
  minicatSerialLCD_I2C:"Miniweergave",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Letter", 
  catInterruptExt:"Onderbroken",
  catDivers:"De belangrijkste cycli",
  title: "Nederlands",
  blocks: "Block",
  verifyTooltip: "Verify sketch",
  uploadTooltip: "Upload sketch",
  linkTooltip: "Opslaan en linken naar blokken.",
  runTooltip: "Opslaan in formaat ino",
  saveXMLTooltip:"Opslaan XML",
  loadXMLTooltip:"Downloaden XML",
  copycodeTooltip:"Kopieer de code Arduino",
  badCode: "Programmeerfout:\n%1",
  timeout: "Het maximum aantal uitvoeringen is overschreden.",
  discard: "Verwijderen %1 blokken?",
  trashTooltip: "Verwijder alle blokken.",
  catLogic: "Logica",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Fiets",
  catMath: "Wiskunde",
  catText: "Tekst",
  catArray:"Array",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Array",
  catGenericTime:"Systemisch",
  catAllVar:"Variabele",
  catVariables: "Eenvoudig",
  catFunctions: "Eenvoudig",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
