var MSG = {
xStepper:"x پله",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c نشانگر",
  nminicatSerialLCD_I2C:"نمایش 84",
  catST2046:"نمایش 2.8",
  fingerprinting:"اثر انگشت",
  tensorsensor:"بار سلول",
  electrocardiography:"کاردیوگرافی",
  catInOut:"ورود / خروج",
  catDigital:"دیجیتال",
  catAnalog:"آنالوگ",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"سریال نرم",
  ibuttonds1990:"کلید",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"موتور",
  catMotorMRT:"رانندگان",
  catServoRot:"سروو 360",
  stepcatServoRot:"سروو 180S",
  catStepper:"قدم گذاشتن 4",
  catStepper28BYJ:"قدم گذاشتن 5",
  catServo:"سروو 180",
  catStorage:"محل ذخیره سازی",
  catLedStrip:"آدرس رهبری",
  catST7735:"نمایش TFT",
  catTM1637:"4/7с نمایش",
  catRTCDS3231:"ماژول DS3231",
  catRTCDS1302:"ماژول DS1302",
  catCommunication:"ماژول های ارتباطی",
  catMAX7219_7D:"8/7с نمایش",
  catMAX7219_LM:"ماتریس 8 8",
  catEEprom:"EEPROM",
  catmicroSD:"کارت حافظه SD",
  catSimpleSensorsALL:"سنسورها",
  catSimpleSensors:"سنسورها 1",
  catSimpleSensors2: "سنسورها 2",
  catSimpleSensors3: "سنسورها 3",
  catOtherSensors:"سنسورهای دیگر",
  catOtherActuators:"ماژول های صدا",
  catRadioTEA5767:"ماژول رادیویی",
  catDFPlayerMP3:"پخش کننده MP3",
  catKeypad:"صفحه کلید",
  catds18b20:"دماسنج",
  catADXL345:"شتاب سنج",
  catTCS3200:"ردیاب رنگ",
  catCamera:"Camera VC0706",
  catHMC5883:"قطب نما",
  bmpcatHMC5883:"فشارسنج",
  catRotaryEncoder:"رمزگذار",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"ماژول های خروجی",
  catDisplay:"نمایش می دهد",
  catRFID:"ماژول کارت",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"نمایش 16 2",
  catSerialLCDmb2:"نمایش 128 64",
  catSerialLCD_I2C:"نمایش 16 2 I2C",
  minicatSerialLCD_I2C:"نمایشگر کوچک",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"حروف کوچک", 
  catInterruptExt:"وقفه",
  catDivers:"چرخه اصلی",
  title: "زبان فارسی",
  blocks: "Block",
  linkTooltip: "ذخیره و پیوند به بلوک.",
  runTooltip: "ذخیره به عنوان ino",
  saveXMLTooltip:"ذخیره کنید XML",
  loadXMLTooltip:"بارگیری XML",
  copycodeTooltip:"کپی کردن کد Arduino",
  badCode: "خطای برنامه:\n%1",
  timeout: "حداکثر تعداد تکرارهای اجرایی فراتر رفته است.",
  discard: "بلوک ها را حذف کنید %1",
  trashTooltip: "همه بلوک ها را حذف کنید",
  catLogic: "منطق",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "چرخه",
  catMath: "ریاضی",
  catText: "متن",
  catArray:"آرایه ها",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"زمان",
  catGenericTime:"سیستم",
  catAllVar:"متغیرها",
  catVariables: "ساده",
  catFunctions: "توابع",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
