var MSG = {
xStepper:"x Stepper",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c indicador",
  nminicatSerialLCD_I2C:"Exibição 84x84",
  catST2046:"Exibição 2.8",
  fingerprinting:"Impressão digital",
  tensorsensor:"Célula de carga",
  electrocardiography:"Cardiógrafo",
  catInOut:"Entrada / Saída",
  catDigital:"Digital",
  catAnalog:"Analogue",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motores",
  catMotorMRT:"Drivers",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Pisar 4",
  catStepper28BYJ:"Pisar 5",
  catServo:"Servo 180",
  catStorage:"Local de armazenamento",
  catLedStrip:"Endereço Led",
  catST7735:"TFT Exibição",
  catTM1637:"4/7с Exibição",
  catRTCDS3231:"Módulo DS3231",
  catRTCDS1302:"Módulo DS1302",
  catCommunication:"Comunicações",
  catMAX7219_7D:"8/7с Exibição",
  catMAX7219_LM:"Matrix 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Cartão SD",
  catSimpleSensorsALL:"Sensores",
  catSimpleSensors:"Sensores 1",
  catSimpleSensors2: "Sensores 2",
  catSimpleSensors3: "Sensores 3",
  catOtherSensors:"Outros sensores",
  catOtherActuators:"Módulos de som",
  catRadioTEA5767:"Módulo de rádio",
  catDFPlayerMP3:"MP3 Jogador",
  catKeypad:"Teclado",
  catds18b20:"Termômetro",
  catADXL345:"Acelerômetro",
  catTCS3200:"Detector de cores",
  catCamera:"Camera VC0706",
  catHMC5883:"Bússola",
  bmpcatHMC5883:"Barómetro",
  catRotaryEncoder:"Codificador",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Módulos de saída",
  catDisplay:"Exibe",
  catRFID:"Módulo de Cartão",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Exibição 16x2",
  catSerialLCDmb2:"Exibição 128×64",
  catSerialLCD_I2C:"Exibição 16x2 I2C",
  minicatSerialLCD_I2C:"Mini Exibição",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Minúsculas", 
  catInterruptExt:"Interrupção",
  catDivers:"Ciclos principais",
  title: "Portugues",
  blocks: "Block",
  linkTooltip: "Salve e vincule aos blocos.",
  runTooltip: "Salvar como ino",
  saveXMLTooltip:"Salvar XML",
  loadXMLTooltip:"Baixar XML",
  copycodeTooltip:"Copiar código Arduino",
  badCode: "Erro de programa:\n%1",
  timeout: "O número máximo de iterações de execução foi excedido.",
  discard: "Excluir %1 blocos?",
  trashTooltip: "Exclua todos os blocos.",
  catLogic: "Lógica",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Ciclo",
  catMath: "Matemática",
  catText: "Text",
  catArray:"Matrizes",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Tempo",
  catGenericTime:"Sistema",
  catAllVar:"Variáveis",
  catVariables: "Simples",
  catFunctions: "Funções",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
