var MSG = {
  xStepper:"x Шаговый",
  leonardo:"Leonardo",
  catInOut:"Вход/Выход",
  catDigital:"Цифровой",
  catAnalog:"Аналоговый",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"Контак ключ",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Моторы",
  catMotorMRT:"Драйверы",
  catServoRot:"Серво 360",
  stepcatServoRot:"Серво 180S",
  catStepper:"Шаговый 4",
  catStepper28BYJ:"Шаговый 5",
  catServo:"Серво 180",
  catStorage:"Место хранения",
  catLedStrip:"Led Адресная",
  catST7735:"TFT Дисплей",
  catTM1637:"4/7с Дисплей",
  catRTCDS3231:"Модуль DS3231",
  catRTCDS1302:"Модуль DS1302",
  catCommunication:"Модули связи",
  catMAX7219_7D:"8/7с Дисплей",
  catMAX7219_LM:"Матрица 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Карта SD",
  catSimpleSensorsALL:"Сенсоры",
  catSimpleSensors:"Сенсоры 1",
  catSimpleSensors2: "Сенсоры 2",
  catSimpleSensors3: "Сенсоры 3",
  catOtherSensors:"Другие сенсоры",
  catOtherActuators:"Звуковые модули",
  catRadioTEA5767:"Радио модуль",
  catDFPlayerMP3:"MP3 Плеер",
  catKeypad:"Клавиатура",
  catds18b20:"Термометр",
  catADXL345:"Акселерометр",
  catTCS3200:"Детектор цвета",
  catCamera:"Camera VC0706",
  catHMC5883:"Компас",
  bmpcatHMC5883:"Барометр",
  catRotaryEncoder:"Энкодер",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Модули выхода",
  catDisplay:"Дисплеи",
  catRFID:"Карт Модуль",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Дисплей 16x2",
  catSerialLCDmb23:"4/7c индикатор",
  catSerialLCDmb2:"Дисплей 128×64",
  catSerialLCD_I2C:"Дисплей 16x2 I2C",
  minicatSerialLCD_I2C:"Мини дисплей",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Строчные", 
  catInterruptExt:"Прерывание",
  catDivers:"Основные циклы",
  title: "Русский",
  blocks: "Блоки",
  linkTooltip: "Сохранить и связать с блоками.",
  runTooltip: "Сохранить в формате ino",
  saveXMLTooltip:"Сохранить XML",
  loadXMLTooltip:"Загрузить XML",
  copycodeTooltip:"Скопировать код Arduino",
  badCode: "Ошибка программы:\n%1",
  timeout: "Превышено максимальное количество итераций выполнения.",
  discard: "Удалить %1 блоки?",
  trashTooltip: "Удалить все блоки.",
  catLogic: "Логика",
  catWIFI:"WiFi",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catr433:"R433 Mhz",
  catLoops: "Цикл",
  catMath: "Математика",
  catText: "Текст",
  catArray:"Массивы",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Время",
  catGenericTime:"Системное",
  catAllVar:"Переменные",
  catVariables: "Простые",
  catFunctions: "Функции",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block.",
  nminicatSerialLCD_I2C:"Дисплей 84x84",
  catST2046:"Дисплей 2.8",
  fingerprinting:"Дактилоскопия",
  tensorsensor:"Тензодатчик",
  electrocardiography:"Кардиограф"
};
