var MSG = {
xStepper:"x Adımlayıcı",
leonardo:"Leonardo",
catSerialLCDmb23:"4/7c gösterge",
  nminicatSerialLCD_I2C:"Ekran 84x84",
  catST2046:"Ekran 2.8",
  fingerprinting:"Parmak izi",
  tensorsensor:"Tenso sensörü",
  electrocardiography:"Kardiyografide",
  catInOut:"Giriş / Çıkış",
  catDigital:"Dijital",
  catAnalog:"Analog",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"iButton",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Motorlar",
  catMotorMRT:"Sürücüler",
  catServoRot:"Servo 360",
  stepcatServoRot:"Servo 180S",
  catStepper:"Step 4",
  catStepper28BYJ:"Step 5",
  catServo:"Servo 180",
  catStorage:"Depolama",
  catLedStrip:"LED Adreslenebilir",
  catST7735:"TFT Monitör",
  catTM1637:"4/7с Monitör",
  catRTCDS3231:"Modül DS3231",
  catRTCDS1302:"Modül DS1302",
  catCommunication:"İletişim modülleri",
  catMAX7219_7D:"8/7с Monitör",
  catMAX7219_LM:"Matris 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"SD kart",
  catSimpleSensorsALL:"Sensörler",
  catSimpleSensors:"Sensörler 1",
  catSimpleSensors2: "Sensörler 2",
  catSimpleSensors3: "Sensörler 3",
  catOtherSensors:"Diğer sensörler",
  catOtherActuators:"Ses modülleri",
  catRadioTEA5767:"Radyo modülü",
  catDFPlayerMP3:"MP3 Volkmen",
  catKeypad:"Klavye",
  catds18b20:"Termometre",
  catADXL345:"İvmeölçer",
  catTCS3200:"Renk dedektörü",
  catCamera:"Camera VC0706",
  catHMC5883:"Pusula",
  bmpcatHMC5883:"Barometre",
  catRotaryEncoder:"Kodlayıcı",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Çıkış modülleri",
  catDisplay:"Monitörler",
  catRFID:"Kart Modülü",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Monitör 16x2",
  catSerialLCDmb2:"Monitör 128×64",
  catSerialLCD_I2C:"Monitör 16x2 I2C",
  minicatSerialLCD_I2C:"Mini ekran",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Küçük harf", 
  catInterruptExt:"Kesinti",
  catDivers:"Ana döngüler",
  title: "Türk",
  blocks: "Block",
  linkTooltip: "Kaydet ve bloklara bağla.",
  runTooltip: "Formatta Kaydet ino",
  saveXMLTooltip:"Kaydetmek XML",
  loadXMLTooltip:"İndir XML",
  copycodeTooltip:"Kodu kopyala Arduino",
  badCode: "Program hatası:\n%1",
  timeout: "Maksimum yürütme yineleme sayısı aşıldı.",
  discard: "Kaldırmak %1 Bloklar?",
  trashTooltip: "Tüm blokları Kaldır.",
  catLogic: "Mantık",
  catWIFI:"WiFi",
  catr433:"R433 Mhz",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catLoops: "Çevrim",
  catMath: "Matematik",
  catText: "Metin",
  catArray:"Diziler",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Zaman",
  catGenericTime:"Sistemli",
  catAllVar:"Değişkenler",
  catVariables: "Basitler",
  catFunctions: "İşlevler",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
