var MSG = {
  xStepper:"x Кроковий",
  leonardo:"Leonardo",
  catInOut:"Ввід/вивід",
  catDigital:"Цифровий",
  catAnalog:"Аналоговий",
  catSerialAll:"USB",
  catSerial:"Serial COM",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Soft Serial",
  ibuttonds1990:"Контак ключ",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT HC-06",
  catWIFISoftSerial:"WiFi ESP8266",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote",
  catMotors:"Мотори",
  catMotorMRT:"Драйвери",
  catServoRot:"Серво 360",
  stepcatServoRot:"Серво 180S",
  catStepper:"Кроковий 4",
  catStepper28BYJ:"Кроковий 5",
  catServo:"Серво 180",
  catStorage:"Місце збереження",
  catLedStrip:"Led Адресна",
  catST7735:"TFT Дисплей",
  catTM1637:"4/7с Дисплей",
  catRTCDS3231:"Модуль DS3231",
  catRTCDS1302:"Модуль DS1302",
  catCommunication:"Модулі зв'язку",
  catMAX7219_7D:"8/7с Дисплей",
  catMAX7219_LM:"Матриця 8х8",
  catEEprom:"EEPROM",
  catmicroSD:"Карта SD",
  catSimpleSensorsALL:"Сенсори",
  catSimpleSensors:"Сенсори 1",
  catSimpleSensors2: "Сенсори 2",
  catSimpleSensors3: "Сенсори 3",
  catOtherSensors:"Інші сенсори",
  catOtherActuators:"Звукові модулі",
  catRadioTEA5767:"Радіо модулі",
  catDFPlayerMP3:"MP3 Плеєр",
  catKeypad:"Клавіатура",
  catds18b20:"Термометр",
  catADXL345:"Акселерометр",
  catTCS3200:"Детектор кольору",
  catCamera:"Camera VC0706",
  catHMC5883:"Компас",
  bmpcatHMC5883:"Барометр",
  catRotaryEncoder:"Енкодер",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Модули виводу",
  catDisplay:"Дисплеї",
  catRFID:"Карт Модуль",
  catSerialLCD:"Serial LCD",
  catSerialLCDm:"Дисплей 16x2",
  catSerialLCDmb23:"4/7c індикатор",
  catSerialLCDmb2:"Дисплей 128×64",
  catSerialLCD_I2C:"Дисплей 16x2 I2C",
  minicatSerialLCD_I2C:"Міні дисплей",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Рядкові", 
  catInterruptExt:"Переривання",
  catDivers:"Основні цикли",
  title: "Українська",
  blocks: "Блоки",
  linkTooltip: "Зберегти та зв'язати з блоками.",
  runTooltip: "Зберегти у форматі ino",
  saveXMLTooltip:"Зберегти XML",
  loadXMLTooltip:"Завантажити XML",
  copycodeTooltip:"Скопіювати код Arduino",
  badCode: "Помилка програми:\n%1",
  timeout: "Перевищено максимальну кількість ітерацій виконання.",
  discard: "Видалити %1 блоки?",
  trashTooltip: "Видалити всі блоки.",
  catLogic: "Логіка",
  catWIFI:"WiFi",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"NRF",
  catRF24L01:"NRF 24L01",
  catr433:"R433 Mhz",
  catLoops: "Цикл",
  catMath: "Математика",
  catText: "Текст",
  catArray:"Масиви",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Час",
  catGenericTime:"Системне",
  catAllVar:"Змінні",
  catVariables: "Прості",
  catFunctions: "Функції",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block.",
  nminicatSerialLCD_I2C:"Дисплей 84x84",
  catST2046:"Дисплей 2.8",
  fingerprinting:"Дактилоскопія",
  tensorsensor:"Тензодатчик",
  electrocardiography:"Кардіограф"
};
